version: '3'

networks:
  laravel:
  walletmicroservicecore_laravel:
    external: true
  walletmicroservicepaypoint_laravel:
    external: true
  walletmicroservicenchl_laravel:
    external: true
  walletmicroservicecybersource_laravel:
    external: true
  walletmicroservicenpay_laravel:
    external: true
  walletmicroservicemerchant_laravel:
    external: true


services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_backend_wallet
    environment:
      TZ: "Asia/Kathmandu"
    ports:
      - "5067:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
      - phpmyadmin
      - mongo
      - mongo-express
    networks:
      - laravel
      - walletmicroservicecore_laravel
      - walletmicroservicepaypoint_laravel
      - walletmicroservicenchl_laravel
      - walletmicroservicecybersource_laravel
      - walletmicroservicenpay_laravel
      - walletmicroservicemerchant_laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql_backend_wallet
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mysql_backend_wallet
      MYSQL_USER: mysql_backend_wallet
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
      - walletmicroservicecore_laravel
      - walletmicroservicepaypoint_laravel
      - walletmicroservicenchl_laravel
      - walletmicroservicecybersource_laravel
      - walletmicroservicenpay_laravel
      - walletmicroservicemerchant_laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_backend_wallet
    volumes:
      - ./src:/var/www/html:delegated
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini:delegated
    ports:
      - "9033:9000"
    networks:
      - laravel
      - walletmicroservicecore_laravel
      - walletmicroservicepaypoint_laravel
      - walletmicroservicenchl_laravel
      - walletmicroservicecybersource_laravel
      - walletmicroservicenpay_laravel
      - walletmicroservicemerchant_laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer_backend_wallet
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
      - walletmicroservicecore_laravel
      - walletmicroservicepaypoint_laravel
      - walletmicroservicenchl_laravel
      - walletmicroservicecybersource_laravel
      - walletmicroservicenpay_laravel
      - walletmicroservicemerchant_laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan_backend_wallet
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
      - walletmicroservicecore_laravel
      - walletmicroservicepaypoint_laravel
      - walletmicroservicenchl_laravel
      - walletmicroservicecybersource_laravel
      - walletmicroservicenpay_laravel
      - walletmicroservicemerchant_laravel

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_backend_wallet
    restart: always
    ports:
      - 5068:80
    environment:
      PMA_HOST: mysql_backend_wallet
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel
      - walletmicroservicecore_laravel
      - walletmicroservicepaypoint_laravel
      - walletmicroservicenchl_laravel
      - walletmicroservicecybersource_laravel
      - walletmicroservicenpay_laravel
      - walletmicroservicemerchant_laravel

  mongo:
    container_name: mongo-backend
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27019:27017"
    restart: always
    volumes:
      - ./mongo:/data/db
    networks:
      - laravel

  mongo-express:
    container_name: mongo-express-backend
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - "5069:8081"
    networks:
      - laravel

