version: '3'

networks:
  laravel:
  wallet-microservice-core_laravel:
    external: true
  wallet_clearance_laravel:
    external: true
#  walletmicroservicepaypoint_laravel:
#    external: true
#  walletmicroservicenchl_laravel:
#    external: true
#  walletmicroservicecybersource_laravel:
#    external: true
#  walletmicroservicenpay_laravel:
#    external: true
#  walletmicroservicemerchant_laravel:
#    external: true
#  walletmicroservicenps_laravel:
#    external: true


services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_backend_wallet
    environment:
      TZ: "Asia/Kathmandu"
    ports:
      - "5067:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
    depends_on:
      - php
      - mysql
      - phpmyadmin

    networks:
      - laravel
      - wallet-microservice-core_laravel
      - wallet_clearance_laravel
  #      - walletmicroservicepaypoint_laravel
  #      - walletmicroservicenchl_laravel
  #      - walletmicroservicecybersource_laravel
  #      - walletmicroservicenpay_laravel
  #      - walletmicroservicemerchant_laravel
  #      - walletmicroservicenps_laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql_backend_wallet
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-config-file.cnf:/etc/mysql/conf.d/mysql-config-file.cnf
    environment:
      MYSQL_DATABASE: mysql_backend_wallet
      MYSQL_USER: mysql_backend_wallet
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
      - wallet-microservice-core_laravel
      - wallet_clearance_laravel
  #      - walletmicroservicepaypoint_laravel
  #      - walletmicroservicenchl_laravel
  #      - walletmicroservicecybersource_laravel
  #      - walletmicroservicenpay_laravel
  #      - walletmicroservicemerchant_laravel
  #      - walletmicroservicenps_laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_backend_wallet
    volumes:
      - ./src:/var/www/html:delegated
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini:delegated
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
    ports:
      - "9033:9000"
    networks:
      - laravel
      - wallet-microservice-core_laravel
      - wallet_clearance_laravel
  #      - walletmicroservicepaypoint_laravel
  #      - walletmicroservicenchl_laravel
  #      - walletmicroservicecybersource_laravel
  #      - walletmicroservicenpay_laravel
  #      - walletmicroservicemerchant_laravel
  #      - walletmicroservicenps_laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer_backend_wallet
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
      - wallet-microservice-core_laravel
      - wallet_clearance_laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan_backend_wallet
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
      - wallet-microservice-core_laravel
      - wallet_clearance_laravel

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_backend_wallet
    restart: always
    ports:
      - 5068:80
    environment:
      PMA_HOST: mysql_backend_wallet
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel
      - wallet-microservice-core_laravel
      - wallet_clearance_laravel
